default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miles-of-smiles_development
  
test:
  <<: *default
  database: miles-of-smiles_test

production:
  <<: *default
  database: miles-of-smiles_production
  username: miles-of-smiles
  password: <%= ENV['MILES-OF-SMILES_DATABASE_PASSWORD'] %>
